stages:
  - linting

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install flake8 flake8-quotes flake8-import-order pep8-naming
    - flake8 --verbose --import-order-style=google

black_check:
  stage: linting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check --config .black .

pytest:
  stage: linting
  image: python:3.10
  script:
    - pip install django-debug-toolbar
    - pip install -r requirements/dev.txt
    - cd lyceum
    - python manage.py migrate
    - python manage.py test